spring:
  datasource:
    url: jdbc:mysql://pi.home:3306/testing_notifier?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  mail:
    host: smtp.qq.com # 填上自己的邮件服务地址
    username: xxxx@qq.com # 邮箱账号
    password: xxxxx # 邮箱密码