server:
  port: 8080
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://pi.home:3306/oa?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: true
  mvc:
    static-path-pattern: /static/**
  freemarker:
    expose-request-attributes: true
    request-context-attribute: request
logging:
  file:
    name: ./logs/testing-notifier.log # path和name不能同时配置

